### ISSUE TITLE
Expected Version

### ISSUE THREAD

**Issue by henry-hz** [exponentially/extreme#18]
Dear @burmajam , I am building an multi-db adapter for commanded, and I would like to add extreme. He is a heavy user of event version, so before appending events, the framework check if the expected version from the appender is in sync with the last version appended to the stream. Please, let me know if in extreme it works in the same way, and if you have more tips on this feature,
thanks.

https://github.com/work-capital/commanded/tree/master/lib/commanded/storage

**Comment by burmajam** [comment]
Hi Henry,

We have places where we are checking event version. We are storing last event number in aggregate and require last_event field in command (which is last known version on client). In handle_exec of GenAggregate we are comparing that command version with aggregate version like:
    
    def handle_exec({:do_something, %{last_event: command_aware_version}}, _from, %{last_event: current_version}=state) when command_aware_version < current_version,
       do: {:noblock, {:error, :concurrency_error, current_version, command_aware_version, state.last_changed_by}, state}

To conclude: Extreme gives us opportunity to be aware of event number, but if and how we'll use it is in rest of the application (GenAggregate and command handler in our case).

    def apply_events({:ok, aggregate, key, events}) do
      case DB.save_aggregate_events(@db, key, events) do
        {:ok, last_event_number} -> Aggregate.apply aggregate, events, last_event_number
        :ok -> :ok 
      end
    end

One more thing about getting event number from Extreme. When writing to stream:

    {:ok, result} = Extreme.execute extreme_pid, write_events(stream_id, events)
    {:ok, result.last_event_number}

On push:

    defmodule MyApp.MyListener do
      use   Extreme.FanoutListener
  
      defp process_push(push) do
        event_id = push.event.event_number
        #...
      end
    end

**Comment by henry-hz** [comment]
thanks! today commanded is using a router that listen to all streams, and route events to process managers. yesterday chatting, I suggested that every process manager subscribe for the interested streams, instead of having a central point for all messages. do you agree? anyway for the way things are now, we would need a subscribe_for_all_events, does extreme support this subscription ? I thought that the command router could start the process manager, like this: 

![seq](https://cloud.githubusercontent.com/assets/1010008/20969999/2912cab6-bc94-11e6-934b-888909e8549b.png)

**Comment by burmajam** [comment]
The way I prefer to use listeners is per category. For example my users app writes to users-123 stream for user 123 and so on. Then you turn on projection per category and you get $ce-users indexed stream. Then on read sides I'm listening that indexed stream. If I need to listen other indexed streams in the same app that's ok as well. We do that a lot.

For all events there's $all indexed stream you can subscribe to, but I don't recommend use of that since it includes internal ES events as well (i.e. $statsCollected).

Just pay attention when using indexed streams and event numbers. There's event.event.event_number (event number in users-123 stream) and event.link.event_number which is event number of indexed stream (that is >= users-123 stream event_number). Link number is what you want to remember what last event listener processed and event.event_number is version of event you want to use for concurrency check.

**Comment by burmajam** [comment]
Also, advantage of using indexed streams per category is that your listeners are processing (at least should process) events synchronously. But if you have 2 indexed streams and 2 listeners those will be processed in parallel. That's advantage but also something you should bare in your mind. It can also produce problems if one depends on other (you are relying that first one has been processed already and you are relying on that processed data for foreign key for example)

**Comment by henry-hz** [comment]
I have just saw your answer now.. sent you an email with the commanded issue.
thanks, that's make sense.
