### ISSUE TITLE
EventStore 4

### ISSUE THREAD

**Issue by drozzy** [exponentially/extreme#35]
The obligatory eventstore 4 issue :-)

It's out, and there seem to be some tcp changes here:
https://geteventstore.com/blog/20170323/event-store-4.0.0-released/index.html

I'm currently using extreme with EventStore 4-rc2, seemingly without problems. Can I upgrade to 4?

**Comment by mjaric** [comment]
I could say from release notes that it won't work without

1. Update protobuff file
2. Implementation of client identity message which is first thing which should be sent to server on connection before any heartbeat

The other stuff should be good since int to long transition os not afevting this library

You are free to do PR or you can wait us to do upgrade

Thank you

**Comment by burmajam** [comment]
Thank you @drozzy for reporting. We are planning to support ES 4 during April.

**Comment by asheehan** [comment]
Any idea on a timeframe for this?

**Comment by burmajam** [comment]
We've planned to do this few months ago, but lack of Mac download postponed this. I'll check docker container these days (but it is not marked as official). I'll let you know as soon as we make some progress.

**Comment by burmajam** [comment]
Hi guys. I've pushed new branch [ES-4](https://github.com/exponentially/extreme/tree/es-4). Can you try it please? Tests are passing on Travis but on my local machine 3-5 tests fail because ES in docker container is much slower (it looks as it is slower ~20x).

You'll have to **add EXTREME_ES_VERSION=4 env var in build time!** (I've added it in config/test.exs) Optional is connection_name: :some_name in extreme configuration. It is also set in config/test.exs

**Comment by burmajam** [comment]
Version of extreme that supports ES 4 is pushed to hex as 0.11.0 version

**Comment by drozzy** [comment]
Thanks for the beautiful work.
