### ISSUE TITLE
Read model : subscribe to all

### ISSUE THREAD

**Issue by BroiSatse** [exponentially/extreme#37]
Hi all,

Just wanted to ask if there is a way to subscribe to all events or, ideally, subscribe to all streams by regex or wildcard matching? I had a quick look at defined messages but the only thing I found is ReadAllEvent, I assume it does not start subscription?

**Comment by mjaric** [comment]
If I'm not wrong the all linked event stream, the built in one, is named $all. Just subscribe to it or read events. There is streams projection also which can be enabled in evenstore db which index NO 1 event of each stream. But it is not valid in case you soft delete some stream and then you write again into it, new first event will have event number incremented by one as last event number was written in that stream before it was deleted. This event will not be captured by streams projection and it will not give you accurate list in ES in such scenario. The rule is that you never reveal deleted stream by no means. 

There is also option to build either query or custom projection. With projection you can calculate some meaningful state which can be also partitioned, eg. Stream ids from each event which occur in es. The state can be retrived with rest api, so far it was not exposed over tcp connection commands

All this you can find in documentation of event store. We didnt build any common scenario since there is not one :) so what ever you can do in ES with indexing, partitioning etc you can read with extreme.

 I advise you to go trough ES docs and try to figure out what Greg was thinking it should resolve and how he model it.
