### ISSUE TITLE
Deadlock while doing concurrent reads and writes

### ISSUE THREAD

**Issue by tonyvanriet** [exponentially/extreme#45]
Hi @burmajam,

We have a few apps that use Extreme to maintain a subscription to a stream while also writing to other streams. These apps would spontaneously crash from GenServer timeouts or Extreme would stop with reason `:tcp_closed`.

We isolated it down to what appears to be a deadlock that can occur while doing basic reads and writes concurrently using the same Extreme worker process. I'll post a PR in a moment with the stress test I've been using to reproduce the deadlock. #46

I got this far a few weeks ago and haven't been able to find time to dig any further, so I thought I'd at least make you aware. We've been able to work-around the problem by using separate Extreme workers for the subscription and the writes.

**Comment by slashdotdash** [comment]
Have you tried using persistent subscriptions as each subscription uses its own connection to the Event Store. Therefore it shouldn't suffer from the issue you mention as writes will be using a separate connection from subscriptions.

**Comment by mjaric** [comment]
This is back pressure issue, heartbeat is not sent back to eventstore server, so server closed connection. @tonyvanriet in your pull request, you piled up instantly 7000 events into extreme process mailbox and additionally refilled it with events from subscriptions, so each time few fanout to eventstore, they are returned back to samo mailbox at the end of it. 

Now, heartbeat is additional event which is sent back and forth between es and  extreme. There is some number of ms (i'm not sure at the moment how much) if extreme do not respond to heartbeat, event store will close connection. So with your extreme process where events are constantly keeping 7000 messages (you are receiving what you sent, right :) )  it is hard for extreme to even take heartbeat message at all. 

This could be fixed, if we pingback heartbeat on reception (:gen_tcp.recv), but that would mean that we have to change tcp communication and instead of `:inet.setopts(socket, active: :once)` we should do gen_tcp.recv with number of bytes we are expecting to find in wire, and decode those bytes in place just to see if it is heartbeat... But this will not give better performance, I think output would be similar. 

There is ,though, one possible solution, but it would make writing async call. Where extreme could collect events into 2 messages stashes in process state, just to keep mailbox as shortest as possible. And each time before it do anything, it should check first if there is heartbeat request in "urgency" stash and if it is, respond to it first. This could resolve `:tcp_closed` issue, but throughput would be similar.

**Comment by tonyvanriet** [comment]
@slashdotdash 
We still haven't tinkered with the persistent subscriptions, but that does sound like another way we could work around the issue. Thanks.

@mjaric 
To be clear, the test in my PR doesn't do anything with subscriptions. It's just doing simple reads and writes. I can't rule out that this is just congestion, but I think there is some evidence to the contrary.

I do recall seeing a forum post where Greg Young mentioned that data traffic will satisfy the EventStore's heartbeat check, though I can't find it in the documentation. It doesn't start sending a separate ping message unless the connection is idle, hence my suspicion that there is a logical deadlock happening preventing traffic flow entirely.
The behavior during the failure also seems to be consistent with a deadlock. During the test, traffic is flowing normally, then suddently stops and the next test read and write don't complete. The test hangs in that state for several seconds until there's either a GenServer timeout or the EventStore closes the connection. It really seems to me that some race condition leads to a state where Extreme is unable to send the `GenServer.reply` that's necessary to complete the `:execute` calls that the test is making for the read and write.
I should try dumping the state of the mailboxes during the test, but I suspect that they're not filling up because each read and write from the test is a synchronous `handle_call(:execute)` call.

Also, if the issue were caused by congestion, I don't think we would have seen the failure in our production scenario. We have very light traffic in production on both the subscription and the writes. And there was no burst of activity correlated with the failure.

Anyway, as I mentioned, we're doing just fine with the workaround. I would need to dig further to be really sure that we're not just misusing the client.

@mjaric If you can find the time to run the test yourself, I'd love to know if you can reproduce it as well.

**Comment by mjaric** [comment]
This is solved in latest release (0.10.3) it shouldn't freeze anymore

**Comment by tonyvanriet** [comment]
Hi @mjaric, looking forward to putting this fix into production.
Is it true that this fix is in the 10.3 release though? That release is dated 11/7 but your deadlock fix is dated 11/13.
