### ISSUE TITLE
EventStore 4.1 compatibility and Elixir 1.6?

### ISSUE THREAD

**Issue by drozzy** [exponentially/extreme#55]
Haven't tried it with 4.1, but does extreme support it?

Same thing for Elixir 1.6?

**Comment by burmajam** [comment]
Hi @drozzy. We didn’t try extreme with ES 4.1 yet but we surely do it since we were unsatisfied with 4.0 performance. Regarding Elixir 1.6, extreme works well with it even though there are warnings. We are planning to fix it but we lack some free time for that

**Comment by pgermishuys** [comment]
@burmajam what kind of performance issues have you noticed with Event Store 4.0?

**Comment by burmajam** [comment]
[This test](https://github.com/exponentially/extreme/blob/master/test/extreme_test.exs#L452) was ~30% slower. Also there's no macOS version ready for download. It's not a blocker but it would be better if it was there as before

**Comment by mjaric** [comment]
I did testing, and I think confusion came with the fact that we are using MacOS and since 4.x version was released MacOS build was discontinued. This led us to run EventStore 4 in docker. What we haven't noticed is that docker-machine by default is configured to run on single vCore and that is invisible bottleneck in test.

Anyways, slowdown is still present since ES 4 has enriched projection engine, but difference is not more than 5-10% 

So final benchmark is (single vCore)

| es version | 500 apends of 2 events | 500 writes in explicit transaction | write 1000 events in signle batch |
|------------|------------------------|------------------------------------|--------------------------|
| 3.9.3      | avg 2300ms             | avg 879ms                          | avg 213ms |
| 4.1.1      | avg 2500ms             | avg 968ms                          | avg 227ms |

Please note that above benchmark is with turned on projection engine where $by_category and $streams projections are started

Without projection engine, append style benchmark is about half second better (I didn't test writes with explicit transaction)

I think the difference is not significant, and this test is not the way how Event Sourcing works, I doubt anyone have case to write from a single thread 1000 events split in 500 batches/transactions :)

EDIT:

I did test with 1000 events in single append to event store stream, and it took around 200ms ;)

**Comment by burmajam** [comment]
Extreme version 0.12.1 is just released with ES 4 tests and supporting elixir 1.6
